{% set name = "microgen" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/3MAH/microgen/archive/v{{ version }}.tar.gz
  sha256: 3e34ee7ff7c09ad2a70da9d34e5a856d14ff4a0dc4933bd3afc49c6756d188ea

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - pip
  run:
    - python >=3.8,<3.12
    - numpy <2
    - vtk
    - pyvista
    - python-gmsh
    - meshio
    - cadquery
    - scipy


test:
  imports:
    - microgen
  requires:
    - pytest
  source_files:
    - tests
    - examples/BasicShapes/platon/tetrahedron.obj
  commands:
    - pytest tests

about:
  home: https://github.com/3MAH/microgen
  summary: 'Microstructure generation'
  description: |
    Microgen is a Python library designed to facilitate microstructure generation and meshing.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://microgen.readthedocs.io
  dev_url: https://github.com/3MAH/microgen

extra:
  recipe-maintainers:
    - kmarchais
    - chemiskyy
    - ricardo0115
