{% set name = "microgen" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/3MAH/microgen/archive/v{{ version }}.tar.gz
  sha256: 39ed4ff16c4629843a3170483755a0ae9251e07c0708b205f0e3d189301a0abf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}, <3.13
    - numpy
    - vtk
    - pyvista
    - python-gmsh
    - meshio
    - cadquery
    - scipy


test:
  imports:
    - microgen
  requires:
    - python {{ python_min }}
    - pytest
  source_files:
    - tests
    - examples/BasicShapes/platon/tetrahedron.obj
  commands:
    - pytest tests

about:
  home: https://github.com/3MAH/microgen
  summary: 'Microstructure generation'
  description: |
    Microgen is a Python library designed to facilitate microstructure generation and meshing.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://microgen.readthedocs.io
  dev_url: https://github.com/3MAH/microgen

extra:
  recipe-maintainers:
    - kmarchais
    - chemiskyy
    - ricardo0115
